### ISSUE TITLE
Mr.Plotter from Docker image doesn't start

### ISSUE THREAD

**Issue by ChristophGehbauer** [immesys/smartgridstore#10]
Hello BTrDB team,
I tried to start up the Docker devmachine and the start_devmachine.sh script works fine. However, when I try to access the Mr.Plotter interface I only get: ï¿½ as response.
I'm running Ubuntu 16.04.
Please let me know what could be the issue, or if you need additional debug information.
Thank you!
Christoph

**Comment by samkumar** [comment]
How are you accessing the Mr. Plotter interface? Are you using HTTPS?

**Comment by ChristophGehbauer** [comment]
Hello Sam,
Thanks for the hint. I was not connecting via https. It works now!
Have a good weekend,
Christoph
