### ISSUE TITLE
btrdb: scaling is undocumented

### ISSUE THREAD

**Issue by lilvinz** [immesys/smartgridstore#14]
When increasing the number of replicas for the btrdb statefulset more nodes are joining the cluster and sharing? the streams. When connecting to btrdb-bootstrap service a random? node is chosen and odds are that it is not responsible for the desired stream. I do not understand how this can work. Am i missing something relevant?

**Comment by immesys** [comment]
`btrdb-bootstrap` is used for clients within the kubernetes cluster to communicate with BTrDB. It will pick a random node, and the client will then ask that node for the MASH table which tells it which nodes are responsible for which streams. The client then connects to the correct BTrDB nodes directly.

Clients outside the kubernetes cluster need to connect to `apifrontend` which will relay the requests to the correct servers.

**Comment by lilvinz** [comment]
Thanks for the explanation.

I made a simple python script to pull content from rabbitmq into btrdb. This is running inside kubernetes and using cluster dns to discover btrdb-bootstrap service. This seems not to work with more than one replica of btrdb. Should the client lib automagically ask for the MASH table and reconnect or is there some action required?

**Comment by immesys** [comment]
Nope, it should work fine with more than one replica, assuming you give it enough time for rebalancing after you scale up (usually a few seconds, depending on load). What do you mean by "not work"? Are you getting an error?

**Comment by lilvinz** [comment]
```
Traceback (most recent call last):
  File "rabbitmq2btrdb.py", line 153, in <module>
    consumeMessages(channel, queue_name)
  File "rabbitmq2btrdb.py", line 80, in consumeMessages
    stream.insert(cache[ident][collection]['tuples'])
  File "/usr/local/site-packages/btrdb4/__init__.py", line 532, in insert
    version = ep.insert(self.uu, thisBatch)
  File "/usr/local/site-packages/btrdb4/endpoint.py", line 141, in insert
    BTrDBError.checkProtoStat(result.stat)
  File "/usr/local/site-packages/btrdb4/utils.py", line 185, in checkProtoStat
    raise stat
btrdb4.utils.BTrDBError: [405] (405: This is the wrong endpoint for this stream)
```

**Comment by immesys** [comment]
BTrDB might still be rebalancing. You can watch the logs and see how it is progressing. The speed depends on the speed of your journal ceph pool.

EDIT: the python bindings are primarily designed for speaking to the APIFrontend. The go bindings are used within the cluster. Try switching your endpoint to the API frontend.

**Comment by lilvinz** [comment]
```
State changed: 
CLUSTER STATE e247621
  LEADER: btrdb-1-000 @247618
  MASH: 22 (2 members, contiguous)
  STATE: Healthy
  NODENAME     STATUS       MASH   WEIGHT RPREF
  btrdb-0-003  up+in        22     100    1.00 
  btrdb-1-000  up+in        22     100    1.00 
ACTIVE MASH
[10f1ee77]  btrdb-0-003 : 0 - 2147483648 (100)
[37b64673]  btrdb-1-000 : 2147483648 - 4294967296 (100)
 NO PROPOSED MASH
```

**Comment by lilvinz** [comment]
Thanks. I will try using the apifrontend instead.

**Comment by lilvinz** [comment]
After fighting with enforced TLS, this leads to another issue:
```
Traceback (most recent call last):
  File "rabbitmq2btrdb.py", line 153, in <module>
    consumeMessages(channel, queue_name)
  File "rabbitmq2btrdb.py", line 75, in consumeMessages
    uuid.uuid4(), encodedCollection)
  File "/usr/local/site-packages/btrdb4/__init__.py", line 137, in create
    self.ep.create(uu, collection, tags, annotations)
  File "/usr/local/site-packages/btrdb4/endpoint.py", line 91, in create
    BTrDBError.checkProtoStat(result.stat)
  File "/usr/local/site-packages/btrdb4/utils.py", line 185, in checkProtoStat
    raise stat
btrdb4.utils.BTrDBError: [406] a stream already exists in that collection with identical tags
```
The flow of operation in the python script is to check if a stream exists and if not create it.

The script is working on ~14000 streams and caching them.

**Comment by immesys** [comment]
Can you share your code?

**Comment by lilvinz** [comment]
https://gist.github.com/lilvinz/6fc37c293c6130ff0c6be7ba8b6694f1

this works when connecting to btrdb-bootstrap with 1 replica of btrdb

**Comment by immesys** [comment]
I don't immediately see anything wrong with your code. It's true that LookupStreams is done with serializable consistency, but the way your application is written, you should always have the stream cached if you had created it before.

The only thing I can conclude is that somehow you are ending up with two streams that have the same collection and same tags. If you check through your log output from the `logging.debug('%s create stream %s field %s ', data['LDAT1_PhyNam_ident'], stream.uuid(), k)` line, do you see any duplicates?

EDIT: I would also edit that logging line to put the collection in and move it before the create call

**Comment by immesys** [comment]
BTW as an aside if you are doing stress testing you will need to adjust the `btrdb/throttle` parameters inside the admin console. A good default might be something like:
```
btrdb/throttle> show
resource             pool   queue 
----------------------------------
ceph_cold            100    10000 
ceph_hot             100    10000 
concurrent_op        5000   5000  
max_conns            100    100   
open_read_trees      5000   5000  
open_trees           5000   5000 
```

**Comment by immesys** [comment]
Perhaps adjust the caching so you merge the streams rather than overwrite. That will solve the problem. Otherwise if you are checking based on lookup rather than uuid, you need to handle the possibility of the already existing error from create.

**Comment by lilvinz** [comment]
That problem aside i am struggling to insert data sufficiently fast but seem not to put any relevant load on the btrdb at all (e.g. concurrent_op is never higher than 3). I assume the problem to be the fact that i have to insert single tuples into lots of different streams.

Imagine 400 tables each having around 40 rows and rabbitmq emits one json per row to insert.

Here is another try at python this time prebuffering to try to insert more than one tuple at once: https://gist.github.com/lilvinz/bfa2ddf4ef73687f3584708ebe8bbb36

Didn't really help though.

e.g. 16 workers like this altogether insert ~700 tuples / s

**Comment by immesys** [comment]
I didn't read it too closely, but it looks like the Lookup is still on the hot path. I would write it so that you hit the cache and only perform the Lookup if you miss.

**Comment by lilvinz** [comment]
Thanks, i will double check that.

**Comment by immesys** [comment]
From a similar small-synchronous-insert benchmark (120 points per insert spread across a few workers) you should expect to see something like 3 million points per second (or 25000 commits per second) on a single node. It depends on how many OSDs you have and the performance of your journal pool, but that's the order of magnitude you should be seeing.
