### ISSUE TITLE
Hamilton path

### ISSUE THREAD

**Issue by praftery** [immesys/smartgridstore#2]
Not as important if issue #1 is addressed, but the default path structure for the Hamiltons doesn't make a lot of sense from a user perspective. Something shorter and more descriptive would be clearer. e.g. Hamiltons/[ID]/Air temperature.

![image](https://cloud.githubusercontent.com/assets/7246762/26258154/481e0952-3c78-11e7-8413-72150482ae26.png)

**Comment by immesys** [comment]
We are working on a fix for this. It will be something like
```
<customer>/air_temp/<sensors>
<customer>/lux/<sensors>
```
So the sensor type comes before the sensor.
