### ISSUE TITLE
Intercept values for Mr. Plotter

### ISSUE THREAD

**Issue by praftery** [immesys/smartgridstore#3]
The vertical lines that users can add to a plot read out the x-axis intercept below, which is useful. Can you extend that so it also works for the y-axis?

![image](https://cloud.githubusercontent.com/assets/7246762/26258311/fbadb346-3c78-11e7-9b92-43d5c0ffc425.png)

**Comment by immesys** [comment]
It does that, but you have to click a stream in the legend to select it, so that it knows which axis you want to read out

**Comment by praftery** [comment]
My bad - didn't realize it!
