### ISSUE TITLE
Hamilton unit metadata

### ISSUE THREAD

**Issue by praftery** [immesys/smartgridstore#4]
Unit metadata doesn't appear for the Hamilton timeseries by default. e.g. selecting an air temp sensor timeseries shows up as y1, as does the data for RH, and all the other sensors.

Also, as much as it pains me to suggest this, many of the prospective users (e.g. all of the industry partners in the audience at the CBE meeting) will want to see degrees Fahrenheit as an easy to select option...

![image](https://cloud.githubusercontent.com/assets/7246762/26258540/e8fa52da-3c79-11e7-95de-59e9640266fb.png)
![image](https://cloud.githubusercontent.com/assets/7246762/26258564/0e2e3fee-3c7a-11e7-9659-8f18ffe2650c.png)

**Comment by immesys** [comment]
@samkumar, @gtfierro this is because the archive request does not specify units on the streams. I think the plotter is doing the right thing, we just need pundat to set the 'unit' annotation.
@praftery is the Farenheit thing important enough to warrant either a) switching everything to F or b) reporting duplicate streams, one in F and one in C?

**Comment by gtfierro** [comment]
Yeah, I think it makes sense to do this in the archive request. Should be pretty straightforward to implement, and I can probably do it w/n the next week

**Comment by immesys** [comment]
Can you allow specifying collection+name at the same time? That will solve #2

**Comment by gtfierro** [comment]
Its all basically the same change, so yes

**Comment by praftery** [comment]
I'm not sure what the best approach is for I-P units, but if the CBE thermal comfort tool is anything to go by, people will continually ask you for it if it's not there! 

Duplicating temperature streams sounds like a viable quick fix, but it seems wasteful to store all that extra data. There's also the issue of handling other units when they crop up: Watts to BTUs, etc. Even with the Hamiltons, you also have lux to foot-candle (though far less commonly used)...

Is just masking/modifying the values displayed on the axes in the Mr. Plotter plot window feasible? I guess the csv download would still come down in SI, but that seems like less of a problem as I figure anyone downloading the data will be doing some analysis on it anyway...

**Comment by praftery** [comment]
Another option would be to provide a secondary axis on the right of the plot that was in I-P...
