### ISSUE TITLE
Stat summary data in Mr. Plotter

### ISSUE THREAD

**Issue by praftery** [immesys/smartgridstore#5]
Another feature request so feel free to totally ignore. Seeing as it has already been computed, could you display the stat summary data for the selected window of data? e.g. what's the min, max and mean of the temperature data in the highlighted area below?

![image](https://cloud.githubusercontent.com/assets/7246762/26260136/f9d4901e-3c80-11e7-83af-64ce237af86c.png)

**Comment by immesys** [comment]
This has been implemented by PingThings in their plotter
